name: Performance Test

on:
  # Run manually, nightly, and on merges to main
  workflow_dispatch:
  # schedule:
  #   - cron: "0 4 * * *"   # every day at 04:00 UTC
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  k6-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout QA repo
        uses: actions/checkout@v3

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run AR Spike Perf Test
        run: k6 run tests/perf/ar_spike.k6.js