name: Security Scan

on:
  # Run manually, nightly, and on merges to main
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # every day at 03:00 UTC
  push:
    branches: [ "test", "main" ]
  pull_request:
    branches: [ "test", "main" ]

jobs:
  zap-auth:
    runs-on: ubuntu-latest
    name: Auth API Security Scan
    steps:
      - name: Checkout QA repo
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Baseline Scan - Auth API
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: ${{ secrets.AUTH_API_URL }}
          docker_name: 'zaproxy/zap-stable'
          issue_title: 'ZAP Scan Auth API Report'
          fail_action: false
          allow_issue_writing: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP Scan Results - Auth
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-scan-results-auth
          path: |
            report_json.json
            report_md.md
            report_html.html

  zap-langraph:
    runs-on: ubuntu-latest
    name: LangGraph API Security Scan
    steps:
      - name: Checkout QA repo
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Baseline Scan - LangGraph API
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: ${{ secrets.LANGRAPH_API_URL }}
          docker_name: 'zaproxy/zap-stable'
          issue_title: 'ZAP Scan LangGraph API Report'
          fail_action: false
          allow_issue_writing: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP Scan Results - LangGraph
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-scan-results-langraph
          path: |
            report_json.json
            report_md.md